<<<<<<< HEAD
<<<<<<< HEAD
my name is rama'
=======
my name is krishna`
>>>>>>> sree
how r you
=======
CREATE TABLE  "FEE_STUDENT" 
>>>>>>> d95d5d0... Testing
   ("ROLLNO" VARCHAR2(4000), 
	"NAME" VARCHAR2(4000), 
	"EMAIL" VARCHAR2(4000), 
	"SEX" VARCHAR2(4000), 
	"COURSE" VARCHAR2(4000), 
	"FEE" NUMBER, 
	"PAID" NUMBER, 
	"DUE" NUMBER, 
	"ADDRESS" VARCHAR2(4000), 
	"CONTACT" VARCHAR2(4000), 
	 CONSTRAINT "FEE_STUDENT_PK" PRIMARY KEY ("ROLLNO") ENABLE
   )
/

CREATE TABLE  "FEE_ACCOUNTANT" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(4000), 
	"EMAIL" VARCHAR2(4000), 
	"PASSWORD" VARCHAR2(4000), 
	"ADDRESS" VARCHAR2(4000), 
	"CONTACT" VARCHAR2(4000), 
	 CONSTRAINT "FEE_ACCOUNTANT_PK" PRIMARY KEY ("ID") ENABLE
   )
<<<<<<< HEAD
/
=======
/
>>>>>>> d95d5d0... Testing
